# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxCmsNWniweV3IwB4X1herIO5p_VTf54
"""

import pandas as pd
df=pd.read_csv("creditcard.csv")
df.head()

df.info()

# 1. Remove missing values
df = df.dropna()

# 2. Remove duplicates
df = df.drop_duplicates()

# 3. Scale Time & Amount
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['Amount'] = scaler.fit_transform(df[['Amount']])
df['Time'] = scaler.fit_transform(df[['Time']])

# 4. Check final shape
print(df.shape)

df.info()

import matplotlib.pyplot as plt

df['Class'].value_counts().plot(kind='bar')
plt.title("Class Distribution (0 = Normal, 1 = Fraud)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

# Percentage
print(df['Class'].value_counts(normalize=True) * 100)
plt.savefig("class_distribution.png")

plt.figure(figsize=(10,5))
plt.hist(df[df['Class']==0]['Time'], bins=50, alpha=0.5, label='Normal')
plt.hist(df[df['Class']==1]['Time'], bins=50, alpha=0.5, label='Fraud')
plt.legend()
plt.title("Time Distribution of Transactions")
plt.xlabel("Time")
plt.ylabel("Frequency")
plt.show()
plt.savefig("Time Distribution of Transactions.png")

import seaborn as sns

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
plt.savefig("Correlation Heatmap.png")

features = ['Amount']

for feature in features:
    plt.figure()
    sns.kdeplot(df[df['Class']==0][feature], label='Normal')
    sns.kdeplot(df[df['Class']==1][feature], label='Fraud')
    plt.title(f"{feature} Distribution")
    plt.legend()
    plt.show()

from sklearn.ensemble import RandomForestClassifier

X = df.drop('Class', axis=1)
y = df['Class']

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

importances = model.feature_importances_

feature_importance = pd.Series(importances, index=X.columns)
feature_importance.sort_values(ascending=False).head(10).plot(kind='bar')

plt.title("Top 10 Important Features")
plt.show()
plt.savefig("Top 10 Important Features.png")



features = ['Amount']

for feature in features:
    plt.figure()
    sns.boxplot(x=df[feature])
    plt.title(f"Boxplot of {feature}")
    plt.show()

with open("eda_summary.txt", "w") as f:
    f.write("EDA SUMMARY\n")
    f.write("====================\n\n")

    f.write("1. Dataset Shape:\n")
    f.write(str(df.shape) + "\n\n")

    f.write("2. Class Distribution:\n")
    f.write(str(df['Class'].value_counts()) + "\n\n")

    f.write("3. Class Percentage:\n")
    f.write(str(df['Class'].value_counts(normalize=True) * 100) + "\n\n")

    f.write("4. Missing Values:\n")
    f.write(str(df.isnull().sum()) + "\n\n")

    f.write("5. Top Features:\n")
    f.write(str(feature_importance.sort_values(ascending=False).head(10)) + "\n\n")

from sklearn.model_selection import train_test_split

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train_original = X_train.copy()
y_train_original = y_train.copy()

from imblearn.over_sampling import SMOTE

smote = SMOTE(k_neighbors=1, random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

from imblearn.under_sampling import RandomUnderSampler

under = RandomUnderSampler(random_state=42)

X_train_under, y_train_under = under.fit_resample(X_train, y_train)

from imblearn.over_sampling import SMOTE

smote = SMOTE(k_neighbors=1, random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

import pickle

# Save all versions
pickle.dump((X_train_original, y_train_original), open("train_original.pkl", "wb"))
pickle.dump((X_train_smote, y_train_smote), open("train_smote.pkl", "wb"))
pickle.dump((X_train_under, y_train_under), open("train_under.pkl", "wb"))

# Save test data (same for all)
pickle.dump((X_test, y_test), open("test_data.pkl", "wb"))

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr = LogisticRegression(max_iter=1000)

# Train on SMOTE data (best start)
lr.fit(X_train_smote, y_train_smote)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression (SMOTE)")
print(classification_report(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train_smote, y_train_smote)

y_pred_rf = rf.predict(X_test)

print("Random Forest (SMOTE)")
print(classification_report(y_test, y_pred_rf))

from xgboost import XGBClassifier

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

xgb.fit(X_train_smote, y_train_smote)

y_pred_xgb = xgb.predict(X_test)

print("XGBoost")
print(classification_report(y_test, y_pred_xgb))

from lightgbm import LGBMClassifier

lgb = LGBMClassifier()

lgb.fit(X_train_smote, y_train_smote)

y_pred_lgb = lgb.predict(X_test)

print("LightGBM")
print(classification_report(y_test, y_pred_lgb))

from sklearn.ensemble import IsolationForest

iso = IsolationForest(contamination=0.002)

iso.fit(X_train)

y_pred_iso = iso.predict(X_test)

# Convert output
y_pred_iso = [1 if x == -1 else 0 for x in y_pred_iso]

print("Isolation Forest")
print(classification_report(y_test, y_pred_iso))

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

results = []

def evaluate_model(name, y_pred):
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append([name, acc, precision, recall, f1])

# Add your models
evaluate_model("Logistic Regression", y_pred_lr)
evaluate_model("Random Forest", y_pred_rf)
evaluate_model("XGBoost", y_pred_xgb)
evaluate_model("LightGBM", y_pred_lgb)
evaluate_model("Isolation Forest", y_pred_iso)

# Create DataFrame
results_df = pd.DataFrame(results, columns=[
    "Model", "Accuracy", "Precision", "Recall (Fraud)", "F1 Score"
])

# Sort by Recall (most important)
results_df = results_df.sort_values(by="Recall (Fraud)", ascending=False)

print(results_df)



y_pred_lr = lr.predict(X_test)
y_pred_rf = rf.predict(X_test)
y_pred_xgb = xgb.predict(X_test)
y_pred_lgb = lgb.predict(X_test)

results_df.to_csv("model_comparison.csv", index=False)

from lightgbm import LGBMClassifier

lgb_tuned = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=7,
    random_state=42
)

lgb_tuned.fit(X_train_smote, y_train_smote)

y_pred_tuned = lgb_tuned.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_tuned))

import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

tuning_results = []

def evaluate_model(name, model):
    y_pred = model.predict(X_test)

    tuning_results.append([
        name,
        precision_score(y_test, y_pred),
        recall_score(y_test, y_pred),
        f1_score(y_test, y_pred)
    ])

# Add models (you can modify params and re-run)
evaluate_model("LightGBM Default", lgb)
evaluate_model("LightGBM Tuned", lgb_tuned)

tuning_df = pd.DataFrame(tuning_results, columns=[
    "Model", "Precision", "Recall", "F1 Score"
])

print(tuning_df)

tuning_df.to_csv("hyperparameter_results.csv", index=False)

import matplotlib.pyplot as plt

tuning_df.set_index("Model").plot(kind="bar")
plt.title("Hyperparameter Tuning Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)

plt.savefig("hyperparameter_comparison.png")
plt.close()

import joblib

# Save the trained model
joblib.dump(lgb, "best_model_lgb.pkl")

print("Model saved successfully!")

y_pred = lgb.predict(X_test)

import pandas as pd

results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

results["Fraud_Prediction"] = results["Predicted"].map({
    0: "No",
    1: "Yes"
})

print(results.head())

fraud_labels = pd.Series(y_pred).map({0: "No", 1: "Yes"})

print(fraud_labels.head())

!pip install fastapi uvicorn pyngrok

!ngrok config add-authtoken "...."

!fuser -k 8000/tcp



# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from fastapi import FastAPI
# from pydantic import BaseModel
# import numpy as np
# import joblib
# 
# app = FastAPI()
# 
# # Load trained model
# model = joblib.load("best_model_lgb.pkl")
# 
# # Input schema (same as training features)
# class Transaction(BaseModel):
#     Time: float
#     V1: float
#     V2: float
#     V3: float
#     V4: float
#     V5: float
#     V6: float
#     V7: float
#     V8: float
#     V9: float
#     V10: float
#     V11: float
#     V12: float
#     V13: float
#     V14: float
#     V15: float
#     V16: float
#     V17: float
#     V18: float
#     V19: float
#     V20: float
#     V21: float
#     V22: float
#     V23: float
#     V24: float
#     V25: float
#     V26: float
#     V27: float
#     V28: float
#     Amount: float
# 
# @app.get("/")
# def home():
#     return {"message": "Fraud Detection API Running"}
# 
# @app.post("/predict")
# def predict(data: Transaction):
# 
#     # IMPORTANT: Maintain exact feature order as training
#     input_data = np.array([[
#         data.Time, data.V1, data.V2, data.V3, data.V4,
#         data.V5, data.V6, data.V7, data.V8, data.V9,
#         data.V10, data.V11, data.V12, data.V13, data.V14,
#         data.V15, data.V16, data.V17, data.V18, data.V19,
#         data.V20, data.V21, data.V22, data.V23, data.V24,
#         data.V25, data.V26, data.V27, data.V28, data.Amount
#     ]])
# 
#     prediction = model.predict(input_data)[0]
#     probability = model.predict_proba(input_data)[0][1]
# 
#     return {
#         "Fraud Prediction": int(prediction),
#         "Fraud Probability": float(probability)
#     }

import subprocess

process = subprocess.Popen(
    ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
)

!pkill ngrok

from pyngrok import ngrok
import time

time.sleep(5)

public_url = ngrok.connect(8000)
print(public_url)

!pip install streamlit requests

!pkill streamlit
!pkill uvicorn
!pkill ngrok

import subprocess

subprocess.Popen([
    "uvicorn", "main:app",
    "--host", "0.0.0.0",
    "--port", "8000"
])

from pyngrok import ngrok

api_url = ngrok.connect(8000)
print("API URL:", api_url)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# 
# st.title("💳 Fraud Detection System")
# 
# st.write("Enter transaction details:")
# 
# # Input fields
# Time = st.number_input("Time", value=0.0)
# 
# V1 = st.number_input("V1", value=0.0)
# V2 = st.number_input("V2", value=0.0)
# V3 = st.number_input("V3", value=0.0)
# V4 = st.number_input("V4", value=0.0)
# V5 = st.number_input("V5", value=0.0)
# V6 = st.number_input("V6", value=0.0)
# V7 = st.number_input("V7", value=0.0)
# V8 = st.number_input("V8", value=0.0)
# V9 = st.number_input("V9", value=0.0)
# V10 = st.number_input("V10", value=0.0)
# V11 = st.number_input("V11", value=0.0)
# V12 = st.number_input("V12", value=0.0)
# V13 = st.number_input("V13", value=0.0)
# V14 = st.number_input("V14", value=0.0)
# V15 = st.number_input("V15", value=0.0)
# V16 = st.number_input("V16", value=0.0)
# V17 = st.number_input("V17", value=0.0)
# V18 = st.number_input("V18", value=0.0)
# V19 = st.number_input("V19", value=0.0)
# V20 = st.number_input("V20", value=0.0)
# V21 = st.number_input("V21", value=0.0)
# V22 = st.number_input("V22", value=0.0)
# V23 = st.number_input("V23", value=0.0)
# V24 = st.number_input("V24", value=0.0)
# V25 = st.number_input("V25", value=0.0)
# V26 = st.number_input("V26", value=0.0)
# V27 = st.number_input("V27", value=0.0)
# V28 = st.number_input("V28", value=0.0)
# 
# Amount = st.number_input("Amount", value=0.0)
# 
# if st.button("Predict Fraud"):
# 
#     data = {
#         "Time": Time,
#         "V1": V1, "V2": V2, "V3": V3, "V4": V4,
#         "V5": V5, "V6": V6, "V7": V7, "V8": V8,
#         "V9": V9, "V10": V10, "V11": V11, "V12": V12,
#         "V13": V13, "V14": V14, "V15": V15, "V16": V16,
#         "V17": V17, "V18": V18, "V19": V19, "V20": V20,
#         "V21": V21, "V22": V22, "V23": V23, "V24": V24,
#         "V25": V25, "V26": V26, "V27": V27, "V28": V28,
#         "Amount": Amount
#     }
# 
#     # 🔥 IMPORTANT: must point to /predict endpoint
#     API_URL = "https://nonaristocratical-madelyn-nonfluidic.ngrok-free.dev/predict"
# 
#     try:
#         response = requests.post(API_URL, json=data)
# 
#         if response.status_code == 200:
#             result = response.json()
#             st.success("Prediction successful ✅")
#             st.write("### Result:")
#             st.json(result)
#         else:
#             st.error("Error in prediction ❌")
#             st.write("Status Code:", response.status_code)
#             st.write("Response:", response.text)
# 
#     except Exception as e:
#         st.error("Request failed ❌")
#         st.write(str(e))

import subprocess

subprocess.Popen(["streamlit", "run", "app.py"])



from pyngrok import ngrok

ui_url = ngrok.connect(8501)
print("Streamlit URL:", ui_url)